
on:
  push:
    tags:
      - 'v*'

name: Desktop

env:
  NODE_VERSION: 14.17.0
  SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}

jobs:

  windows:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: |
          iwr https://get.secrethub.io/windows | iex
          (get-item (where.exe secrethub)).DirectoryName | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - run: |
          echo "ELECTRON_WINDOWS_CERT_BASE64=$(secrethub read denniske/aoe2companion/electron_windows_cert_base64)" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=$(secrethub read denniske/aoe2companion/electron_windows_cert_password)" >> $GITHUB_ENV

      - run: echo "VERSION=$(node deploy/script/version-from-tag.js $TRAVIS_BRANCH)" >> $GITHUB_ENV
      - run: echo $VERSION

      - name: Build
        run: |
          echo $ELECTRON_WINDOWS_CERT_BASE64 | base64 --decode > certificate.pfx
          yarn
          yarn npe version $VERSION
          yarn run build

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist2\Winget UI ${{ env.VERSION }} Portable.exe
          tag: ${{ github.ref }}
          overwrite: true
